spring:
  application:
    name: TimeZoneProject

  datasource:
    url: jdbc:mysql://localhost:3306/synctime?useSSL=false&serverTimezone=UTC
    username: root
    password: MysqlLogin_19
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Consider changing to 'validate' or 'none' in production
    show-sql: true
server:
  port: 8083
eureka:
  client:
    registerWithEureka: true        # Registers this service with the Eureka server
    fetchRegistry: true             # Fetches the registry from the Eureka server
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server to connect with
  instance:
    hostname: localhost             # The hostname of the instance
    instance-id: "${spring.application.name}:${instanceId:${random.value}}"